[package]
name = "testing"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "^0.4"
env_logger = "^0.11"
#
# Collections
indexmap = "^2.7"
#
# Random
rand = "^0.8"
